In [ ]:
import sqlite3
conn = sqlite3.connect('test.db')

print ("Opened database successfully")

Opened database successfully


In [ ]:
conn.execute('''CREATE TABLE IF NOT EXISTS tweets(
				category TEXT,
				tweetDate DATE,
				count INTEGER,
				tweet TEXT NOT NULL
        );''')
print ("Table created successfully");


Table created successfully


In [ ]:
import csv
# Creating a cursor object to execute SQL queries on a database table
cursor = conn.cursor()
contents = csv.reader('/content/EVGamingTweetData.csv', delimiter='\t')
# Reading the contents of the StockData.csv file
try:
	#insert_records = f"INSERT INTO tweets (category, tweetDate, count, tweet) VALUES(?, ?, ?, ?)"
 	# Importing the contents of the file into our tweets table
	#cursor.executemany(insert_records, contents)
  conn.execute(f"INSERT INTO tweets (category, tweetDate, count, tweet) VALUES('Health','2022-05-01',2,'@backtolife_2023 @tme_toni I thought the pro #vaccine people wanted depopulation. If so then why do they care about people getting vaccines which supposedly saves lives?')")
  conn.execute(f"INSERT INTO tweets (category, tweetDate, count, tweet) VALUES('Health','2022-05-01',3,'Analysts expect #Pfizers #COVID19 #vaccine sales to drop to $14.2 billion in 2023 from $34.1 billion in 2022. Lets see $PFEs earnings report tomorrow and their 2023 guidance. I expect a limited sell-off.')")
  conn.execute(f"INSERT INTO tweets (category, tweetDate, count, tweet) VALUES('Health','2022-05-01',4,'@beakinderhuman @maxicat12 @MikeSington Lots of supposed2 out there but reality is who knows?Currently,that u can go online pushes much back on people2 do follow up which is very unreliable4 true info.need accurate complete data4 decisions-#Americans deserve solid info4safety in #medicine #vaccines #vaccine #Health')")
  conn.execute(f"INSERT INTO tweets (category, tweetDate, count, tweet) VALUES('Health','2022-05-02',5,'Absolutely ridiculous, OHIP no longer covers online docs 1st #LiberalsMustGo fire/force retired/make quit docs over the #vaccine so a lot of us no longer have a doc NOW we have to PAY $50 per visit 4 a online doc WTF #TrudeauMustGoNow')")
  conn.execute(f"INSERT INTO tweets (category, tweetDate, count, tweet) VALUES('Health','2022-05-02',6,'@HawleyMO So why is insulin so costly but the experimental spike protein shot IS free? Can you answer that? Or do you have blood on your hands too? END THE #vaccine MANDATES NOW.')")
  conn.execute(f"INSERT INTO tweets (category, tweetDate, count, tweet) VALUES('Food','2022-05-01',1,'@fundhunter_co Exactly. I did take a look at $MCD but no topline growth for yrs whereas $sbux does have so I went with $SBUX and $YUMC. $DPZ is a fantastic growth story. If it dipped I should take a look. Thanks for the hint. I know you did an article on it.')")
  conn.execute(f"INSERT INTO tweets (category, tweetDate, count, tweet) VALUES('Food','2022-05-01',2,'@OptionsLocator $MCD SAYS MCRIB WILL BE ON SCHEDULE FOR MAY $MCD hahah')")
  conn.execute(f"INSERT INTO tweets (category, tweetDate, count, tweet) VALUES('Food','2022-05-01',3,'SunTrust Robinson Humphrey Maintains Buy on McDonald')")
  conn.execute(f"INSERT INTO tweets (category, tweetDate, count, tweet) VALUES('Food','2022-05-02',4,'MCDONALDS SAYS WILL REOPEN 15 RESTAURANTS IN UK ON MAY 13')")
  conn.execute(f"INSERT INTO tweets (category, tweetDate, count, tweet) VALUES('Food','2022-05-02',5,'$WEN limiting burgers to 2oz. Americas are going to be all over $MCD frozen patties for the next few months. I believe I read that they have a 6 month supply in the free')")
except sqlite3.Error as error:
    print({error})
    pass


# SQL query to retrieve all data from the tweets table to verify that the
# data of the csv file has been successfully inserted into the table
select_all = f"SELECT * FROM tweets"
rows = cursor.execute(select_all).fetchall()

# Output to the console screen
print({"Rows written" : len(rows)})

# Committing the change

# closing the database connection

{'Rows written': 10}


In [ ]:

#!pip install pandas seaborn numpy
#!pip install torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio===0.11.0+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html
!pip install transformers
#!pip install tqdm



Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.7/6.7 MB 47.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.6/7.6 MB 60.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.2/199.2 KB 19.8 MB/s eta 0:00:00


In [ ]:
import torch

import pandas as pd
import numpy as np
from scipy.special import softmax

from time import sleep
import json
import os

from collections import namedtuple

from tqdm.notebook import tqdm

from transformers import AutoTokenizer, AutoModelForSequenceClassification

In [ ]:
model_type = f"cardiffnlp/twitter-roberta-base-sentiment-latest"

tokenizer = AutoTokenizer.from_pretrained(model_type)
model = AutoModelForSequenceClassification.from_pretrained(model_type)

Some weights of the model checkpoint at cardiffnlp/twitter-roberta-base-sentiment-latest were not used when initializing RobertaForSequenceClassification: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [ ]:
def all_sentiment_scores(tweet):
    """To return the sentiment score of a Tweet as analysed by BERTweet. """
    tokens = tokenizer.encode(tweet, return_tensors='pt')
    result = model(tokens)
    return softmax(result.logits.detach().numpy())

In [ ]:
def max_sentiment_score(tweet):
    """To return the sentiment score of a Tweet as analysed by BERTweet. """
    return np.argmax(all_sentiment_scores(tweet)) - 1

In [ ]:
cursor = conn.execute("SELECT * from tweets")
for row in cursor:
  print(all_sentiment_scores(row[3]))

[[0.6017007  0.37408715 0.02421219]]
[[0.47673693 0.4934593  0.02980379]]
[[0.3739715  0.57773536 0.04829313]]
[[0.9164777  0.07764221 0.00588008]]
[[0.89134145 0.1020126  0.00664592]]
[[0.02984899 0.23284803 0.737303  ]]
[[0.00946639 0.54533535 0.44519827]]
[[0.00962353 0.9154595  0.07491702]]
[[0.00723228 0.8035614  0.18920635]]
[[0.0561076 0.7824263 0.1614661]]


In [ ]:
df=pd.read_csv('/content/tweetdataset.csv',on_bad_lines='skip',delimiter='\t')
df.columns=['Category','Date','Tweet']
df.head()

Category        Date                                              Tweet
0   Health  2023-01-30  Analysts expect #Pfizer's #COVID19 #vaccine sa...
1   Health  2023-01-30  @beakinderhuman @maxicat12 @MikeSington Lots o...
2   Health  2023-01-30  Absolutely ridiculous, OHIP no longer covers o...
3   Health  2023-01-30  @HawleyMO So why is insulin so costly but the ...
4   Health  2023-01-30  With all these "covid" related cardiac arrests...

In [ ]:
df['Score']=df['Tweet'].apply(all_sentiment_scores)
df.head()

Category        Date                                              Tweet  \
0   Health  2023-01-30  Analysts expect #Pfizer's #COVID19 #vaccine sa...   
1   Health  2023-01-30  @beakinderhuman @maxicat12 @MikeSington Lots o...   
2   Health  2023-01-30  Absolutely ridiculous, OHIP no longer covers o...   
3   Health  2023-01-30  @HawleyMO So why is insulin so costly but the ...   
4   Health  2023-01-30  With all these "covid" related cardiac arrests...   

                                      Score  
0     [[0.5059379, 0.4673429, 0.026719155]]  
1    [[0.37397128, 0.5777356, 0.048293162]]  
2  [[0.91647774, 0.07764218, 0.0058800806]]  
3  [[0.89134145, 0.102012604, 0.006645926]]  
4      [[0.7881991, 0.18264747, 0.0291534]]

In [ ]:
df['neg_score']=''
df['neu_score']=''
df['pos_score']=''
for i in range(len(df['Score'])):
  df['neg_score'][i]=df['Score'][i][0][0]
  df['neu_score'][i]=df['Score'][i][0][1]
  df['pos_score'][i]=df['Score'][i][0][2]
df.head()

Category        Date                                              Tweet  \
0   Health  2023-01-30  Analysts expect #Pfizer's #COVID19 #vaccine sa...   
1   Health  2023-01-30  @beakinderhuman @maxicat12 @MikeSington Lots o...   
2   Health  2023-01-30  Absolutely ridiculous, OHIP no longer covers o...   
3   Health  2023-01-30  @HawleyMO So why is insulin so costly but the ...   
4   Health  2023-01-30  With all these "covid" related cardiac arrests...   

                                      Score neg_score neu_score pos_score  
0     [[0.5059379, 0.4673429, 0.026719155]]  0.505938  0.467343  0.026719  
1    [[0.37397128, 0.5777356, 0.048293162]]  0.373971  0.577736  0.048293  
2  [[0.91647774, 0.07764218, 0.0058800806]]  0.916478  0.077642   0.00588  
3  [[0.89134145, 0.102012604, 0.006645926]]  0.891341  0.102013  0.006646  
4      [[0.7881991, 0.18264747, 0.0291534]]  0.788199  0.182647  0.029153

In [ ]:
df['MaxScore']=df['Tweet'].apply(max_sentiment_score)
df.head()

Category        Date                                              Tweet  \
0   Health  2023-01-30  Analysts expect #Pfizer's #COVID19 #vaccine sa...   
1   Health  2023-01-30  @beakinderhuman @maxicat12 @MikeSington Lots o...   
2   Health  2023-01-30  Absolutely ridiculous, OHIP no longer covers o...   
3   Health  2023-01-30  @HawleyMO So why is insulin so costly but the ...   
4   Health  2023-01-30  With all these "covid" related cardiac arrests...   

                                      Score neg_score neu_score pos_score  \
0     [[0.5059379, 0.4673429, 0.026719155]]  0.505938  0.467343  0.026719   
1    [[0.37397128, 0.5777356, 0.048293162]]  0.373971  0.577736  0.048293   
2  [[0.91647774, 0.07764218, 0.0058800806]]  0.916478  0.077642   0.00588   
3  [[0.89134145, 0.102012604, 0.006645926]]  0.891341  0.102013  0.006646   
4      [[0.7881991, 0.18264747, 0.0291534]]  0.788199  0.182647  0.029153   

   MaxScore  
0        -1  
1         0  
2        -1  
3        -1  
4        -1

In [ ]:
agg_df = df.groupby(['Category', 'Date']).agg({'neg_score': 'sum','neu_score': 'sum','pos_score': 'sum'})
agg_df

neg_score   neu_score  pos_score
Category Date                                         
EVs      2023-01-30     0.86252    0.126337   0.011143
         2023-02-03    5.382128     7.59715   6.020722
         2023-02-04    2.641864    2.773764   3.584371
Finance  2023-01-30    8.634012   27.519156  15.846827
         2023-01-31    0.062286    3.150732   2.786983
         2023-02-01    0.466918    0.434118   3.098964
         2023-02-02    2.615557   10.345776  21.038666
         2023-02-03    2.637196    19.46015  12.902657
         2023-02-04    5.511716    11.97042  12.517864
Health   2023-01-30   160.48056     92.4077  23.111769
         2023-01-31  169.563782   94.347496  27.088739
         2023-02-01  139.759018  107.274002   25.96693
         2023-02-02  150.408081  101.067047  29.524923
         2023-02-03    31.61557   11.454193   2.930235
         2023-02-04   19.358704   14.341728   6.299565
Tech     2023-01-30    9.394297   17.930798  17.674908
         2023-01-31   19.531878   41.363571  20.104551
         2023-02-01     5.87379   16.306807  16.819405
         2023-02-02   29.569504   60.399071  21.031414
         2023-02-03   29.507996   27.968248   6.523758
         2023-02-04   21.184486    29.47093   13.34459
Telecom  2023-01-30   16.318724   18.432673   4.248604
         2023-01-31    7.562849    5.152617   0.284534
         2023-02-01    5.827374    5.831487   0.341139
         2023-02-02   20.940828     45.0746  10.984566
         2023-02-03   14.578438   13.219346   5.202213
         2023-02-04   24.214348   22.095627   3.690021

In [ ]:
agg_df1 = df.groupby(['Category', 'Date', 'MaxScore'])['MaxScore'].count().reset_index(name='Count')
pivoted_df = agg_df1.pivot_table(index=['Category', 'Date'], columns='MaxScore', values='Count', fill_value=0)
pivoted_df = pivoted_df.reset_index()
pivoted_df.columns=['Category','Date','Neg_count','Neu_count','Pos_count']
pivoted_df

Category        Date  Neg_count  Neu_count  Pos_count
0       EVs  2023-01-30          1          0          0
1       EVs  2023-02-03          7          6          6
2       EVs  2023-02-04          3          3          3
3   Finance  2023-01-30          7         30         15
4   Finance  2023-01-31          0          3          3
5   Finance  2023-02-01          1          0          3
6   Finance  2023-02-02          0         13         21
7   Finance  2023-02-03          3         20         12
8   Finance  2023-02-04          5          9         16
9    Health  2023-01-30        172         89         15
10   Health  2023-01-31        200         70         21
11   Health  2023-02-01        156        102         15
12   Health  2023-02-02        174         83         24
13   Health  2023-02-03         44          0          2
14   Health  2023-02-04         20         15          5
15     Tech  2023-01-30         11         14         20
16     Tech  2023-01-31         18         51         12
17     Tech  2023-02-01          4         21         14
18     Tech  2023-02-02         30         74          7
19     Tech  2023-02-03         33         28          3
20     Tech  2023-02-04         24         29         11
21  Telecom  2023-01-30         18         18          3
22  Telecom  2023-01-31         10          3          0
23  Telecom  2023-02-01          6          6          0
24  Telecom  2023-02-02         26         48          3
25  Telecom  2023-02-03         18         10          5
26  Telecom  2023-02-04         29         21          0

In [ ]:
finaldf=pd.merge(pivoted_df,agg_df,left_on='Category',right_on='Category')
final_df = finaldf.groupby(['Category', 'Date']).agg({'neg_score': 'sum','neu_score': 'sum','pos_score': 'sum','Neg_count': 'sum','Neu_count': 'sum','Pos_count': 'sum'})
final_df

neg_score   neu_score   pos_score  Neg_count  Neu_count  \
Category Date                                                                   
EVs      2023-01-30    8.886513   10.497252    9.616236          3          0   
         2023-02-03    8.886513   10.497252    9.616236         21         18   
         2023-02-04    8.886513   10.497252    9.616236          9          9   
Finance  2023-01-30   19.927685   72.880356   68.191956         42        180   
         2023-01-31   19.927685   72.880356   68.191956          0         18   
         2023-02-01   19.927685   72.880356   68.191956          6          0   
         2023-02-02   19.927685   72.880356   68.191956          0         78   
         2023-02-03   19.927685   72.880356   68.191956         18        120   
         2023-02-04   19.927685   72.880356   68.191956         30         54   
Health   2023-01-30   671.18573  420.892151  114.922165       1032        534   
         2023-01-31   671.18573  420.892151  114.922165       1200        420   
         2023-02-01   671.18573  420.892151  114.922165        936        612   
         2023-02-02   671.18573  420.892151  114.922165       1044        498   
         2023-02-03   671.18573  420.892151  114.922165        264          0   
         2023-02-04   671.18573  420.892151  114.922165        120         90   
Tech     2023-01-30  115.061951  193.439423   95.498627         66         84   
         2023-01-31  115.061951  193.439423   95.498627        108        306   
         2023-02-01  115.061951  193.439423   95.498627         24        126   
         2023-02-02  115.061951  193.439423   95.498627        180        444   
         2023-02-03  115.061951  193.439423   95.498627        198        168   
         2023-02-04  115.061951  193.439423   95.498627        144        174   
Telecom  2023-01-30   89.442558  109.806351   24.751076        108        108   
         2023-01-31   89.442558  109.806351   24.751076         60         18   
         2023-02-01   89.442558  109.806351   24.751076         36         36   
         2023-02-02   89.442558  109.806351   24.751076        156        288   
         2023-02-03   89.442558  109.806351   24.751076        108         60   
         2023-02-04   89.442558  109.806351   24.751076        174        126   

                     Pos_count  
Category Date                   
EVs      2023-01-30          0  
         2023-02-03         18  
         2023-02-04          9  
Finance  2023-01-30         90  
         2023-01-31         18  
         2023-02-01         18  
         2023-02-02        126  
         2023-02-03         72  
         2023-02-04         96  
Health   2023-01-30         90  
         2023-01-31        126  
         2023-02-01         90  
         2023-02-02        144  
         2023-02-03         12  
         2023-02-04         30  
Tech     2023-01-30        120  
         2023-01-31         72  
         2023-02-01         84  
         2023-02-02         42  
         2023-02-03         18  
         2023-02-04         66  
Telecom  2023-01-30         18  
         2023-01-31          0  
         2023-02-01          0  
         2023-02-02         18  
         2023-02-03         30  
         2023-02-04          0

In [ ]:
for i in range(len(finaldf['Score'])):
  df['wt_neg'][i]=df['Score'][i][0][0]*df['Count']
  df['wt_neu'][i]=df['Score'][i][0][1]*df['Count']
  df['wt_pos'][i]=df['Score'][i][0][2]*df['Count']
df.head()

In [ ]:
p_bar = tqdm(enumerate(df['Tweet']))
for indx, row in p_bar:
  jsonCopy = json.loads(row["Data"])
                #jsonCopy['score'] = sentiment_score(jsonCopy['tweet'][:135])
  sentiments = all_sentiment_scores(jsonCopy['tweet'])
  jsonCopy['neg_score'] = sentiments[0][0]
  jsonCopy['neu_score'] = sentiments[0][1]
  jsonCopy['pos_score'] = sentiments[0][2]
  max_sentiment = max_sentiment_score(jsonCopy['tweet'])
  jsonCopy['is_neg'] = jsonCopy['count'] if max_sentiment == -1 else 0
  jsonCopy['is_neu'] = jsonCopy['count'] if max_sentiment == 0 else 0
  jsonCopy['is_pos'] = jsonCopy['count'] if max_sentiment == 1 else 0    
                